FROM python:3.9-slim

WORKDIR /app

# Install Git
RUN apt-get update 
RUN apt-get install -y --no-install-recommends git
RUN apt-get purge -y --auto-remove
RUN rm -rf /var/lib/apt/lists/*

# Copy files
COPY analyzer/*.py .
COPY analyzer/requirements.txt .
COPY common/*.py ./common/
COPY common/requirements.txt ./common/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r ./common/requirements.txt

# Default environment variables can be overridden at runtime
ENV ANALYSIS_ID=""
ENV GITHUB_URL=""
ENV REDIS_HOST=""
ENV REDIS_PORT=""

CMD ["python", "./worker.py"]