version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LLM_API_KEY=${LLM_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allows the web container to spawn worker containers
    depends_on:
      - redis
      - llm
    networks:
      - redis_net
      - llm_net

  llm:
    build:
      context: .
      dockerfile: Dockerfile.llm
    networks:
      - llm_net

  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - redis_data:/data
    networks:
      - redis_net

  worker:
    build:
      context: .
      dockerfile: Dockerfile.analyzer
    image: analyzer_worker
    command: ["echo", "Worker image built"]
    networks:
      - redis_net

networks:
  redis_net:
    name: redis_net
    driver: bridge
  llm_net:
    name: llm_net
    driver: bridge

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./redis_data
