FROM python:3.9-slim

WORKDIR /app

# Copy files
COPY LLM-Server-Not-Integrated/*.py .
COPY LLM-Server-Not-Integrated/requirements.txt .
COPY common/*.py ./common/
COPY common/requirements.txt ./common/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r ./common/requirements.txt

# Run the FastAPI server on 0.0.0.0:8000
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "1000"]