FROM python:3.9-slim

WORKDIR /app

# Copy files
COPY web-server/*.py .
COPY web-server/requirements.txt .
COPY common/*.py ./common/
COPY common/requirements.txt ./common/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r ./common/requirements.txt

# Run the FastAPI server on 0.0.0.0:8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]